BEGIN TRANSACTION;

INSERT INTO restaurant VALUES(4,'Tasty','Smedjegatan 28, Växjö',047025900,0);
INSERT INTO pizza VALUES(1,'Margeritha',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,2);

INSERT INTO pizza VALUES(2,'Venezia',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,7);

INSERT INTO pizza VALUES(3,'Caruso',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,8);
INSERT INTO p_i VALUES(4,10);

INSERT INTO pizza VALUES(4,'Vesuvio',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);

INSERT INTO pizza VALUES(5,'Calzone (inbakad)',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);

INSERT INTO pizza VALUES(6,'Cappricciosa',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,11);

INSERT INTO pizza VALUES(7,'Capri',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,12);

INSERT INTO pizza VALUES(8,'Hawaii',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,4);

INSERT INTO pizza VALUES(9,'Florida',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,13);

INSERT INTO pizza VALUES(10,'Africana',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,19);
INSERT INTO p_i VALUES(4,4);

INSERT INTO pizza VALUES(11,'Blecko',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,12);
INSERT INTO p_i VALUES(4,11);

INSERT INTO pizza VALUES(12,'Jamaica',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,11);
INSERT INTO p_i VALUES(4,12);

INSERT INTO pizza VALUES(13,'Malta',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,13);
INSERT INTO p_i VALUES(4,12);
INSERT INTO p_i VALUES(4,9);

INSERT INTO pizza VALUES(14,'Madrid',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,18);
INSERT INTO p_i VALUES(4,9);
INSERT INTO p_i VALUES(4,26);
INSERT INTO p_i VALUES(4,27);

INSERT INTO pizza VALUES(15,'Maffia',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,11);
INSERT INTO p_i VALUES(4,14);


INSERT INTO pizza VALUES(16,'Disco',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,12);
INSERT INTO p_i VALUES(4,7);

INSERT INTO pizza VALUES(17,'La Mare',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,11);
INSERT INTO p_i VALUES(4,4);
INSERT INTO p_i VALUES(4,12);

INSERT INTO pizza VALUES(18,'Ciao Ciao (inbakad)',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,9);
INSERT INTO p_i VALUES(4,14);
INSERT INTO p_i VALUES(4,11);
INSERT INTO p_i VALUES(4,10);

INSERT INTO pizza VALUES(19,'Havspizza',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,12);
INSERT INTO p_i VALUES(4,24);
INSERT INTO p_i VALUES(4,22);
INSERT INTO p_i VALUES(4,25);

INSERT INTO pizza VALUES(20,'Kycklingpizza',75,0,1);
INSERT INTO p_i VALUES(4,1);
INSERT INTO p_i VALUES(4,16);
INSERT INTO p_i VALUES(4,28);
INSERT INTO p_i VALUES(4,29);
INSERT INTO p_i VALUES(4,20);

COMMIT;