BEGIN TRANSACTION;

CREATE TABLE "android_metadata" ("locale" TEXT DEFAULT 'en_US');
INSERT INTO android_metadata VALUES('en_US');

CREATE TABLE ingredient (_id INTEGER PRIMARY KEY, name TEXT);

CREATE TABLE p_i (p_id INTEGER, i_id INTEGER);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(2,1);
INSERT INTO p_i VALUES(2,2);
INSERT INTO p_i VALUES(2,3);
INSERT INTO p_i VALUES(4,3);
INSERT INTO p_i VALUES(4,4);

CREATE TABLE pizza (_id INTEGER PRIMARY KEY, name TEXT, price NUMERIC, rating INTEGER, r_id INTEGER);

CREATE TABLE restaurant (_id INTEGER PRIMARY KEY, name TEXT, address TEXT, phone NUMERIC, rating INTEGER);

COMMIT;