BEGIN TRANSACTION;

INSERT INTO restaurant VALUES(1,'Bella Lanterna','Norra Järnvägsgatan 6a, Växjö',047014050,0);
INSERT INTO pizza VALUES(1,'Margherita',79,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,30);

INSERT INTO pizza VALUES(2,'Ruccola',83,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,30);
INSERT INTO p_i VALUES(1,30);
INSERT INTO p_i VALUES(1,30);

INSERT INTO pizza VALUES(3,'Caruso',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,8);
INSERT INTO p_i VALUES(1,10);

INSERT INTO pizza VALUES(4,'Vesuvio',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);

INSERT INTO pizza VALUES(5,'Calzone (inbakad)',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);

INSERT INTO pizza VALUES(6,'Cappricciosa',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(1,11);

INSERT INTO pizza VALUES(7,'Capri',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(1,12);

INSERT INTO pizza VALUES(8,'Hawaii',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(1,4);

INSERT INTO pizza VALUES(9,'Florida',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(1,13);

INSERT INTO pizza VALUES(10,'Africana',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,19);
INSERT INTO p_i VALUES(1,4);

INSERT INTO pizza VALUES(11,'Blecko',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,12);
INSERT INTO p_i VALUES(1,11);

INSERT INTO pizza VALUES(12,'Jamaica',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(1,11);
INSERT INTO p_i VALUES(1,12);

INSERT INTO pizza VALUES(13,'Malta',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,13);
INSERT INTO p_i VALUES(1,12);
INSERT INTO p_i VALUES(1,9);

INSERT INTO pizza VALUES(14,'Madrid',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,18);
INSERT INTO p_i VALUES(1,9);
INSERT INTO p_i VALUES(1,26);
INSERT INTO p_i VALUES(1,27);

INSERT INTO pizza VALUES(15,'Maffia',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(1,11);
INSERT INTO p_i VALUES(1,14);


INSERT INTO pizza VALUES(16,'Disco',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(1,12);
INSERT INTO p_i VALUES(1,7);

INSERT INTO pizza VALUES(17,'La Mare',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,3);
INSERT INTO p_i VALUES(1,11);
INSERT INTO p_i VALUES(1,4);
INSERT INTO p_i VALUES(1,12);

INSERT INTO pizza VALUES(18,'Ciao Ciao (inbakad)',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,9);
INSERT INTO p_i VALUES(1,14);
INSERT INTO p_i VALUES(1,11);
INSERT INTO p_i VALUES(1,10);

INSERT INTO pizza VALUES(19,'Havspizza',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,12);
INSERT INTO p_i VALUES(1,24);
INSERT INTO p_i VALUES(1,22);
INSERT INTO p_i VALUES(1,25);

INSERT INTO pizza VALUES(20,'Kycklingpizza',75,0,1);
INSERT INTO p_i VALUES(1,1);
INSERT INTO p_i VALUES(1,16);
INSERT INTO p_i VALUES(1,28);
INSERT INTO p_i VALUES(1,29);
INSERT INTO p_i VALUES(1,20);

COMMIT;