BEGIN TRANSACTION;

INSERT INTO restaurant VALUES(5,'Roma','Västra Esplenaden 6B, Växjö',047025900,0);

INSERT INTO pizza VALUES(1,'Calzone (inbakad)',60,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,2);
INSERT INTO p_i VALUES(5,3);

INSERT INTO pizza VALUES(2,'Vesuvio',60,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,2);
INSERT INTO p_i VALUES(5,3);

INSERT INTO pizza VALUES(3,'Hawaii',60,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,2);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,4);

INSERT INTO pizza VALUES(4,'Tomaso',60,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,2);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,12);

INSERT INTO pizza VALUES(2,'Venezia',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,7);

INSERT INTO pizza VALUES(3,'Caruso',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,8);
INSERT INTO p_i VALUES(5,10);


INSERT INTO pizza VALUES(6,'Cappricciosa',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,11);

INSERT INTO pizza VALUES(7,'Capri',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,12);


INSERT INTO pizza VALUES(9,'Florida',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,13);

INSERT INTO pizza VALUES(10,'Africana',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,19);
INSERT INTO p_i VALUES(5,4);

INSERT INTO pizza VALUES(11,'Blecko',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,12);
INSERT INTO p_i VALUES(5,11);

INSERT INTO pizza VALUES(12,'Jamaica',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,11);
INSERT INTO p_i VALUES(5,12);

INSERT INTO pizza VALUES(13,'Malta',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,13);
INSERT INTO p_i VALUES(5,12);
INSERT INTO p_i VALUES(5,9);

INSERT INTO pizza VALUES(14,'Madrid',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,18);
INSERT INTO p_i VALUES(5,9);
INSERT INTO p_i VALUES(5,26);
INSERT INTO p_i VALUES(5,27);

INSERT INTO pizza VALUES(15,'Maffia',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,11);
INSERT INTO p_i VALUES(5,14);


INSERT INTO pizza VALUES(16,'Disco',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,12);
INSERT INTO p_i VALUES(5,7);

INSERT INTO pizza VALUES(17,'La Mare',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,3);
INSERT INTO p_i VALUES(5,11);
INSERT INTO p_i VALUES(5,4);
INSERT INTO p_i VALUES(5,12);

INSERT INTO pizza VALUES(18,'Ciao Ciao (inbakad)',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,9);
INSERT INTO p_i VALUES(5,14);
INSERT INTO p_i VALUES(5,11);
INSERT INTO p_i VALUES(5,10);

INSERT INTO pizza VALUES(19,'Havspizza',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,12);
INSERT INTO p_i VALUES(5,24);
INSERT INTO p_i VALUES(5,22);
INSERT INTO p_i VALUES(5,25);

INSERT INTO pizza VALUES(20,'Kycklingpizza',75,0,1);
INSERT INTO p_i VALUES(5,1);
INSERT INTO p_i VALUES(5,16);
INSERT INTO p_i VALUES(5,28);
INSERT INTO p_i VALUES(5,29);
INSERT INTO p_i VALUES(5,20);

COMMIT;